Makefile
README.md
mos.yml

Shelly 2 in relay mode added.
Tested: 
-  manual switches both work as expected
- relays both work as expected
- Reverting back to stock firmware works as expeted..

initial Shelly2 support

---

tools/flash_shelly.sh

This fixes an error that showed only in linux.
```./flash_shelly.sh: line 314: continue: only meaningful in a `for', `while', or `until' loop```

[FlashScript] fix a loop issue in linux.

---

tools/flash_shelly.py

device info is now pulled during the scan process, and stored in a DICT for each device. This also means we can add any missing info during scan like 'app', 'stock_model' in stock fw, and store it in the DICT.
```
info['host'] = f'{host}.local'
info['device_id'] = host
info['app'] = shelly_model(info['type'], 'homekit')
info['stock_model'] = info['type']
info['version'] = info['fw'].split('/v')[1].split('@')[0]
info['fw_type'] = 'stock'
```
Please give a once over, and test, seems fine here.

[FlashScript] Optimise code, add new function "get_info".

---

tools/flash_shelly.py

this adds following:
[FlashScript] add python version check for script, as it requires ver 3.6.x
[FlashScript] add Shelly 1L support.
[FlashScript]  Shelly RGBW2: fix flashing Current Stock firmware.
[FlashScript] small cleanup.
[FlashScript] allow more time to test version, some stock device can take longer than 30 seconds.

[Flashscript] various fixes and small clean up.

---

tools/flash-shelly.py

only show Sys Temp if key exists
allow more time for device to flash and reboot, some stock device's can be slow to perform a flash.
add device count for flash failed devices, only show flashed / failed when in flashing mode.
fix varSeq in version parse.
fix forced version flashing for stock firmware.

[FlashScript] version 2.1.5

---

.github/version.py
.github/workflows/shelly-homekit.yaml

* Add a GitHub action that automatically builds firmware for supported Shelly devices (#379)
* Uses `git describe` to put firmware zips into an appropriately-titled directory e.g. `2.7.3-latest8-geee7898` 
View a sample build [here](https://github.com/ZeevoX/shelly-homekit/runs/1788742790).

Add GitHub action

---

mos.yml
src/shelly_main.cpp

At the moment `BTN_GPIO` will configure `SetupButton` which uses `NoisyInputPin` on ESP8266. Thats a problem for the upcoming RGBW2 support. RGBW2 needs PWM and PWM uses the hardware timer, but the hardware timer is blocked by `NoisyInputPin`. 
In a gitter chat @rojer says that only 1L and 1PM needs `NoisyInputPin`, all other can use `InputPin`.
This PR explizit configures the use of `NoisyInputPin` or `InputPin` for `SetupButton`. That allow the `SetupButton` use and PWM on the RGBW2 at the same time.

use BTN_NOISY to decide useing NoisyInputPin or InputPin

---

fs_src/index.html
fs_src/script.js

Before this change the PayPal donate button was loaded after each web socket response / each sec. With this change it is only loaded once.

load donate button only once

---

fs_src/index.html
fs_src/script.js

Before this change the UI looks broken before the first RPC fetch is done, this PR fix it and make it a bit nicer.
Before:
After:
Note: The Donate buttons are still there, I turned of the wifi to make the screenshots, that's why thy are not in the screen shots.

Load screen

---

fs_src/style.css

Remove some css 💩, saves us some bytes.
We don't need the removed vendor prefixes (`-webkit-`/`-ms`) on our supported browsers.
This changes the layout a bit on non apple devises as it's no longer uses the Light variants of the font, but on apple devises they have never been used.
I didn't find any optical change in this PR on latest Mac Safari

Css cleanup

---

fs_src/style.css

We use a flat design, for me a drop shadow doesn't fit

remove box shadow from help button

---

fs_src/script.js
src/shelly_rpc_service.cpp

We mostly use the wc term for window cover, but at one point we name it `rsh_avail`, this PR unifies the namings.

unify wc naming

---

fs_src/index.html
fs_src/style.css

Revert buttons to her old size and split all double button's into two rows.
(iPhone 8 size)

fix button spinner

---

fs_src/index.html
mos.yml
src/shelly_hap_valve.cpp
src/shelly_switch.cpp

closes #510, I can't find the problem, so I provide a fix which removes the support for valve type Shower Head and Water Faucet. Generic Valve and Irrigation will still work.
If no one can fix #510, we can remove the support of the non working types to unblock v2.8.0.

remove support for valve type Shower Head and Water Faucet

---

fs_src/index.html
fs_src/script.js
mos.yml
src/shelly_hap_switch.cpp
src/shelly_main.cpp
src/shelly_output.cpp
src/shelly_output.hpp
src/shelly_switch.cpp

add invert output option

---

mos.yml
tools/flash-shelly.py

once your happy to merge, let me know and i'll push the 'Version 2.6.0` commit.
- move main script block in to a Class, this makes things easier to maintain.
- rename '-t | --type' to '-ft | --fw-type' and add '-mt | --model-type'.
- add -i | --info-level, default is 2,  1=minimal, 2=basic, 3=all.
- better handling of version compare after flashing (use parsed version)
- use US english for 'color_mode' to match stock firmware.
- make 'scan' the default mode for list and flash, if a manual host is detected scan will not be used.
- tweak list view layout.
- various text changes.

[Flashscript] Version 2.6.0

---

src/shelly_hap_rgb.cpp
src/shelly_hap_rgb.hpp

Incoming h, s, v values should not be used as a reference. References should only be used if method will change them like out-params. There is no performance advantage in this case, because float = 32bit and references are also 32bit. Incoming parameters (larger than 32bit) should use "const 'datatype' &".
The method doesn't change class members, in this case the method should be const.
I also fixed the HSV to RGB calculation, it wasn't working correct
HSV input = H (0-359) S (0-1) V (0-1)
RGB output = R (0-1) G (0-1) B (0-1)
I think it would also be better to declare structs for RGB and HSV values to improve performance. I didn't change that, because there is already a class named RGB in use. In future it should be possible to make a smooth animated transition between 2 colors. In this …

Rework HSV to RGB calculation

---

src/shelly_output.cpp

Thanks to @jobl1978 this hack is no longer needed.
Before:
```
52069217 shelly_hap_rgb.cpp:194  state: on, brightness: 1, hue: 120, saturation: 100
52073495 shelly_output.cpp:74    Output 1: OFF (HAP)
52078227 shelly_output.cpp:71    Output 2: 0.010000 (HAP)
52082336 shelly_output.cpp:74    Output 3: 0.000000 (HAP) # real value was something like 0.0000001
```
After:
```
52069217 shelly_hap_rgb.cpp:194  state: on, brightness: 1, hue: 120, saturation: 100
52073495 shelly_output.cpp:74    Output 1: OFF (HAP)
52078227 shelly_output.cpp:71    Output 2: 0.010000 (HAP)
52082336 shelly_output.cpp:74    Output 3: OFF (HAP)
```

remove rounding issue hack

---

fs_src/index.html
fs_src/script.js

Changes:
1. With this PR the debug link also works in the local frontend dev mode.
2. I see no longer a need to hide the debug link on load as it's always shown after load.

improve log access in local dev mode and always show debug link

---

Makefile
fs_src/index.html

some sed versions can work with newlines, whit them the first command produces
```
<style>nn</style>
```
instead of
```
<style>
</style>
```
same on the script tag
for example it happens with sed of older Mac OS versions, following stackoverflow it maybe also happens with gnu sed.

fix sed commands

---

Makefile

Before this change `LOCAL` would be `-n 1` or `-n 0` so the `ifeq "$(LOCAL)" "1"` can't work.
Tested on macOS, so please test on linux before merging.

fix make script for local

---

README.md

The old list wasn't completed, not every feature was listed every where. If we would expand  that it would be very long.
IMO a table is more clear.
Preview: https://github.com/timoschilling/shelly-homekit/blob/patch-4/README.md

refactor feature list to a table

---

tools/flash-shelly.py

- move run block into Main class, move config, device_scan, manual_hosts into own functions, better handling of webserver shutdown.
- add support for RGBW2 (both stock color modes).
- add support for ShellyMotion (list info only, must use manual IP's and use --timeout 240, as motion needs longer to wake and be detected)
- add -dn | --device-name filter to limit scan to include term.
- add '-f | --flash', '--app-version', '--timeout'
- add battery info for those devices that support it.
- python formatting and cleanup, more optimisations
- add regex literal to re.search lines, suggestion by juanfal thanks. fixes #589
- fix keyboard interrupt for manual hosts.
- if device on stock, but not on latest version, nolonger show latest shock version info, but HomeKit version available.

[Flashscript] Version 2.7.0

---

src/shelly_hap_window_covering.cpp

Currently only a press to the same direction will stop a moving covering.
I changed the behavior in that way that pressing any direction will stop the covering if it is moving. This is the standard behavior of most covering controllers.
Should be linked to the following issue
https://github.com/mongoose-os-apps/shelly-homekit/issues/639

Pressing up or down will always stop a moving window covering

---

src/shelly_hap_rgb.cpp

Internal caching prevented correct switching of initial state (on/off/input).
fixes #645

Force initial state switching for ShellyRGBW2

---

src/shelly_hap_light_bulb.cpp
src/shelly_output.cpp

Clearer to read and should also reduce lagging between timer calls a little bit.
New log output:
```
896655873 shelly_hap_light_bu:273 Transition started... 3000 [ms]
896694004 shelly_hap_light_bu:275 Output 1: 1.00 => 0.50
896730289 shelly_hap_light_bu:276 Output 2: 0.65 => 0.32
896766288 shelly_hap_light_bu:277 Output 3: 0.00 => 0.00
896810333 shelly_hap_light_bu:278 Output 4: 0.00 => 0.00
896859045 shelly_hap_light_bu:525 Brightness read 1: 50
899852427 shelly_hap_light_bu:434 Transition ready
```

Reduce frequent logging during transitions

---

tools/flash-shelly.py

so it does not save info for hosts, if not using security on device.

[Flashscript] tweak save security.

---

Makefile
mos.yml
src/ShellyColorBulb/shelly_init.cpp
src/ShellyDuo/shelly_init.cpp
src/ShellyVintage/shelly_init.cpp

Add Support for Shelly Bulbs.
I have tested this code on Duo E27, Vintage A60, Color Bulb E27 /  GU10.
Shelly Support says that the E27 and GU10 have the same pinout and all Vintages have the same pinout.

Bulb support

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

With this changes it is possible to use GitHub Codespaces out of the box without any additional setup.
I mainly uses Codespaces as dev environment, because the mos docker setup is very slow on Macs.

setup devcontainer for gh codespaces

---

mos.yml
src/shelly_main.cpp

This is primary for the bulb as they don't have any reset button, but I and some other users (see https://github.com/mongoose-os-apps/shelly-homekit/issues/939) found it useful to have it on all devices.
closes #918

Boot reset

---

src/shelly_hap_window_covering.cpp

The `wc.max_ramp_up_time_ms` setting defaults to 5000ms and gives time
for motors to ramp up and draw some real power before we determine
whether they're actually running (by comparing their power draw to the
`wc.idle_power_thr` setting).
When calibrating the window covering _opening_ the calibration logic
waits the whole ramp up time before determining whether the motor is
idle, but this logic is missing when calibrating the closing. There's
just a 1000ms check hard-coded but if the motor takes longer than that
to get going and draw sufficient power the calibration will be deemed
complete (too early).
This patch simply copies the ramp up check from the open calibration
logic to the close calibration logic, which I guess was just forgotten
in f41b01f5854f5.

WC: Respect ramp up time when calibrating close

---

fs_src/script.js
libreset/src/shelly_reset.cpp
src/DS18XXX/shelly_temp_sensor_ow.cpp
src/ShellyUNI/shelly_init.cpp

obviously ubuntu latest docker image changed the clang format version
this lets it pass. esp32 build is still broken, I will have a fix for that also, but its in the Docker image of mongoose-os itself

code format fix for github actions clang-format

---

mos.yml
src/ShellyDuo/shelly_init.cpp
src/ShellyRGBW2/shelly_init.cpp
src/shelly_common.hpp
src/shelly_hap_adaptive_lighting.cpp
src/shelly_hap_adaptive_lighting.hpp
src/shelly_hap_light_bulb.cpp
src/shelly_hap_light_bulb.hpp

I have been working on this for a while, as I really find this an interesting feature.
I think now it is in a state for review and testing.
currently it relies on one additional fix https://github.com/mongoose-os-libs/homekit-adk/pull/10
This adds the Homekit feature adaptive lighting for Lights supporting ColorTemperature (CCT at the moment).
When adaptive lighting is enabled, the light gets a schedule every 24 hours how to adapt the color temperature according to the current night / daytime. Afterwards the schedule is ran on the device itself see e.g. https://www.howtogeek.com/712520/how-to-use-adaptive-lighting-with-apple-homekit-lights/ for how this works.
As this is not (yet) documented in the published Apple Homekit spec, this relies heavily on the reverse engineering of the TLV …

adaptive lighting support for CCT lights

---

fs_src/index.html
mos.yml
src/shelly_hap_garage_door_opener.cpp

My intent for this PR is that I reused a damaged UNI (wiring of in1 is removed) for my garage door. That means it can't work in single mode and can only close in double mode. So I added a second single mode which uses out2 instead of out1 like the current single mode does.

gdo option to use second output

---

tools/flash-shelly.py

zeroconf can return a properties dict like:
{b'': None}
for certain devices.  The HP OfficeJet Pro 9010 is one such device.  This causes update script to display the exception to the user, since the comprehension is expecting all of the values to be strings.

Fix complaint when zeroconf returns props with a value of None

---

.devcontainer/devcontainer.json
.github/workflows/build.yaml
Makefile
README.md
mos.yml
src/ShellyPlus2PM/shelly_init.cpp
src/shelly_main.cpp

This creates a PR from timo's WIP for better overview and discussions
Current Issues
This manifests itself that when stock fw is uploaded, the device boots into old firmware. most likely we override some factory default which is not there afterwards. this can be config0.json, as it is notably NOT shipped with stock fw update
Fixed: this is because the i2c needs to be set in conf according to the model save in shelly partition, otherwise bootloop will occur or revert on OTA downgrade

Plus2PM Support

---

.github/workflows/build.yaml
Makefile
README.md
fs_src/index.html
mos.yml
src/ShellyMini1Gen3/shelly_init.cpp
src/ShellyMini1PMGen3/shelly_init.cpp
src/shelly_output.cpp

TODOS:
PM support for BL0942 (will be done in separate PR cannot be done without HW available)

Support for Mini 1 Gen 3 / Mini 1PM Gen 3 / Plus 1 Mini

---

src/ShellyMini1Gen3/shelly_init.cpp
src/ShellyMini1PMGen3/shelly_init.cpp

To check: if this affects also esp32 devices on newer FWs
include all other GEN3

Fix Mini 1 Gen 3 Relais After update

---

fs_src/index.html
fs_src/script.js
mos.yml
src/shelly_hap_window_covering.cpp
src/shelly_hap_window_covering.hpp

As discussed on #766 
The functionality would be really useful but there have been no follow-ups since 2021...
This entirely escaped my knowledge, but I tried to do it without duplicating window_covering.
Can @rojer @markirb confirm it works as expected? 
Thanks in advance and sorry if there are any inconveniences. I have little to no idea what I'm doing.

Add window support (2)
