mongoose-os-apps/shelly-homekit

.gitignore, README.md, fs/index.html, mos.yml, src/shelly_main.c, src/shelly_sw_service.c
Fixes https://github.com/mongoose-os-apps/shelly-homekit/issues/11
Tested it during this weekend on my garage door with success.
This is my first go at C for 20 years, so a critical eye might be a good idea. 
Cheers!
Johan
=> Added auto off timer feature - Garage door support

README.md, tools/flash_shelly.sh
this pull request add's linux support please review when you have time.
```
pi@soma-connect:~ $ ./flash_shelly.sh -la
Installing jq...
You may be asked for your password...
Reading package lists... Building dependency tree... Reading state information... The following NEW packages will be installed: jq 0 upgraded, 1 newly installed, 0 to remove  Processing triggers for man-db (2.7.6.1-2) ...deb ...ently installed.)peration, 98.3 kB of additional disk space will be used. Selecting previously unselected package jq.
Installing avahi-utils...
You may be asked for your password...
Reading package lists... Building dependency tree... Reading state information... The following NEW packages will be installed: avahi-utils 0 upgraded, 1 newly installed, 0 to remove and 142 not upgraded. Need to get …
```
=> [FlashScript] add Linux support.

README.md, tools/flash_shelly.sh
=> [FlashScript] check for local domain, add automatically if required

tools/flash_shelly.sh
take a look, if OK with you, please pull.
I'll report back once Shelly has responded to my support ticket regarding flash modes.
Thanks
Andy.
=> [FlashScript] add instructions for RGBW2 device.

tools/flash_shelly.sh
usage:
./flash_shelly.sh -f 2.1.2 hostname
#To Do
add support to force flash Stock Firmware Versions.
=> [FlashScript] add -V so you can force a firmware version.

tools/flash_shelly.sh
This removes a simple sleep to a proper wait loop with a max of 30 seconds, before reporting a failure.
=> [FlashScript] refactor "Waiting for device to reboot"

tools/flash_shelly.sh
Add check to make sure the forced version is available for the device you are trying to flash, if not report that it is not available.
Also tweak "Not Supported" to "Not available"
Fix spelling error.
=> [FlashScript] forced version check.

tools/flash_shelly.sh
=> [FlashScript] fix install of required programs.

tools/flash_shelly.sh
Please give a once over, it should all be working.
example `./flash_shelly.sh -ae host1 host2`
=> [FlashScript] add -e 'exclude' hosts option, add some text formatting, and slight code clean up.

tools/flash_shelly.sh
required for flashing to and from different firmware types.
=> [FlashScript] optimise code for detecting shelly model.

tools/flash_shelly.py
please give through test, seems ok here.
=> [FlashScript] initial upload of Python version.

tools/flash_shelly.py
fix an exception catch on JSON error. increase scan time to 10 seconds.
=> [FlashScript]  more optimisation of code, and make code easier to follow.

tools/flash_shelly.py
fix wrong "HomeKit" / "Official" mode labels.
=> [FlashScript] fix 'Latest: xxx' label.

tools/flash_shelly.py
before allowing flashing to HomeKit fw.
i have tested here, but if you could test also, just to be sure it's all ok.
=> [FlashScript] force stock firmware upgrade.

tools/flash_shelly.py
=> [Flashscript] add version check, add some info.

tools/flash_shelly.py
=> [FlashScript] dlurl just check file header exists.

tools/flash-shelly.py
fix possible crash in 'parse_version', Shelly1L has '_1L' in version number.
tweak verbose logging.
allow scanner to timeout if host fails to respond, as this could stop scanner completing a full scan before main scan loop exceeded timeout.
=> [Flashscript] some tweaks and fixes.

tools/flash-shelly.py
add a Queue for scanner.
add '-q', '--quiet'  to only list devices that need to be upgraded.
add some trace debug info for manual hosts.
add helpful web link to fix online version info failure.
add device name, helps to identify a stock device.
remove the need for urllib and use requests.get.
fix 'friendly_host' variable.
fix manual hosts.
some code cleanup.
=> [FlashScript] use Queue for scanner.

tools/flash-shelly.py
streamline flash to HomeKit from none current stock firmware.
move get_device_info out of zeroconf thread.
fix force flash stock url.
fix a couple of exceptions.
debug info added / tweaked.
=> [FlashScript] various fixes and tweaks.

tools/flash-shelly.py
add file logging via --log-file {LOG_FILENAME}
add --verbose levels 0 - 5
add 'flashed_devices' count
=> [FlashScript] Logging tweaks

fs_src/index.html, fs_src/script.js, fs_src/style.css
* use `div`'s `onclick` to teleport user to correct section
* style the mouse pointer so that it is clear that it is clickable
=> Link update alert to the system update section (Fix #303)

tools/flash-shelly.py
[FlashScript] add --type, this allow scan to limit it to firmware type (stock, homekit or all)
[FlashScript] add --ip-type, allows config of Static IP or DHCP.
[FlashScript] move hap-setup-code out of write_flash.
[FlashScript] update usage section.
=> [Flashscript] version 2.2.2

fs_src/script.js
Before:
We have a dedicated logging on some points and a explizit logging if the message send sucessed.
After:
We have always a logging before the message sends and a sucessed / error message after.
=> improve socket logging

fs_src/script.js
This PR switches from js string concatenation to string templates aka string interpolation.
As Rojer says in #475 that we don't want to support IE 11 this works in any current browser.
=> use js string templates

fs_src/index.html, fs_src/script.js
=> [webUI] change relay state control to a slider.

fs_src/index.html, fs_src/script.js, fs_src/style.css
=> improve mobile layout and split system into system and firmware

tools/flash-shelly.py
add support for using IP addresses in manual hosts
add --local-file for support flash local zip files (place zip file in 'tools' folder)
add up time.
`./flash-shelly.py --local-file=firmware.zip shellyrgbw2-xxxxxx.local`
=> [FlashScript] version 2.3.0

tools/flash-shelly.py
hide error message "Could not resolve host:" during flash.
=> [Flashscript] version 2.3.1

tools/flash-shelly.py
don't crash on any issues with remote stock firmware info.
use IP addresses that scanner finds.
=> [FlashScript] version 2.3.3

tools/flash-shelly.py
only get remote info when read to probe devices.
=> [FlashScript] version 2.3.4

tools/flash-shelly.py
split get_remote_info separate functions for fw type
fix Host: label in listing
=> [Flashscript] Version 2.3.5

tools/flash-shelly.py
fix crash if model is missing from remote info.
cosmetic changes.
=> [Flashscript] Version 2.3.6

fs_src/script.js
=> remove double ip label

fs_src/index.html, fs_src/style.css
=> [webui] buttons back to side by side, reduce page width, fix header.

tools/flash-shelly.py
do not lookup remote version info when using local files.
add uptime to Stock firmware.
fix flashing stock firmware fixes #518 
simplify and give more descriptive messages.
tweak some debug info.
=> [Flashscript] Version 2.3.9

tools/flash-shelly.py
optimise 'probe_device' only start webserver once, only pull release info when necessary.
optimise 'get_release_info'
optimise 'get_device_info'
optimise code for version detection.
add HAP connections to list output.
cosmetic tweak.
=> [FlashScript] Version 2.4.0

tools/flash-shelly.py
fix possible early while loop exit.
=> [FlashScript] version 2.5.3

tools/flash-shelly.py
get preboot_uptime before flashing
make sure we can get version info, before we exit loop.
=> [Flashscript] version 2.5.5

tools/flash-shelly.py
tweak wait_for_reboot for stock firmware
add ability to append logging messages, to allow progress dots.
=> [Flashscript] version 2.5.6

tools/flash-shelly.py
fix possible crash.
cleanup 'wait_for_reboot' function.
update regex for more stock version variations.
=> [FlashScript] version 2.5.7

tools/flash-shelly.py
- catch 'KeyboardInterrupt' and handle clean exit (can now CTRL-C to stop scanner).
- fix cometic issue.
- silently ignore unparseable version number.
=> [Flashscript] Version 2.6.1

tools/flash-shelly.py
fix crash for stock now sending '{'status': 'Updating, please wait...'}' in '/rpc/Shelly.GetInfo' during update.
=> Flashscript: Version 2.6.2

tools/flash-shelly.py
optimise 'get_device_info'.
simplify some core code.
-V and --local-file can now be used to force flash over existing version.
add some DNS info to trace logging.
=> [Flashscript] Version 2.6.3

.gitignore, README.md, fs_src/index.html, fs_src/script.js, mos.yml, src/ShellyRGBW2/shelly_init.cpp, src/shelly_hap_rgb.cpp, src/shelly_hap_rgb.hpp, src/shelly_rpc_service.cpp
Now its possible to switch the mode between RGB and RGBW
=> Add RGBW support

fs_src/script.js
=> fix model displaying in the UI

Makefile
I accidentally created #619 with a debug version not with a buildable version
=> fix make script

fs_src/index.html, fs_src/script.js, mos.yml, src/shelly_hap_rgb.cpp, src/shelly_hap_rgb.hpp
Configurable transition time for ON/OFF and color fade
=> Add transition feature for RGBW2

src/shelly_hap_rgb.cpp, src/shelly_hap_rgb.hpp
RGBW2 wasn't able to recover the light (off -> on)  if it was in momentary mode with initial state last
=> Fix initial state of RGBW2

src/ShellyRGBW2/shelly_init.cpp, src/shelly_hap_rgb.cpp
This improves the switching of the rgbw modes and the reboot light flash time.
=> improve rgbw mode switching

tools/flash-shelly.py
- add support for device security `--user | --password`.
- add support for 'flashscript.json', place a file called 'flashscript.json' in the tools folder containing machines and usernames, passwords
- fix stock local file flashing to homekit.
```
{
"security": {
"shellyrgbw2-ABC123.local": {
"user": "admin",
"password": "abcd12345"
},
"shellygas-BDCE566.local": {
"user": "admin",
"password": "zxcvbn"
}
}
```
=> Flashscript: version 2.8.0

fs_src/index.html, fs_src/script.js, fs_src/style.css
Hello everyone, 
this PR contains a field on the form of the shutter which allows the user to set the target position of the shutter. 
Looking forward to hear from you. Regards, Jan
=> Add set position input to shutter forms

fs_src/script.js
=> fix check releases link

fs_src/script.js
=> fix error message for update not found

Makefile, mos.yml, src/ShellyUNI/shelly_init.cpp
closes #479
basic uni support with:
- 2 switches
- 2 inputs
- GDO mode
features for a later PR:
- temp sensors
- ADC
=> add support for Shelly UNI

tools/flash-shelly.py
This PR add the ability to find and update plus devices which already have the HomeKit firmware.
Every think else may follow in different PRs.
=> add support for plus 1(pm) devices with hk fw to flash tool

README.md
Every 1-2 month we have issues like #977
=> Add note to not use Shelly 2 for Dimmer 2

tools/flash-shelly.py
this just cleans up some cosmetic issues.
=> [Script] Cosmetic cleanup.

src/ShellyColorBulb/shelly_init.cpp, src/ShellyDuo/shelly_init.cpp, src/ShellyRGBW2/shelly_init.cpp, src/ShellyVintage/shelly_init.cpp
this needs: https://github.com/mongoose-os-libs/homekit-adk/pull/9
=> bulbs: fix identify for primary accessories

fs_src/style.css
I have introduced CSS variables for common values that are reused. This improves readability and opens up the possibility of adding a dark mode in the future.
=> Introduce CSS variables

fs_src/index.html, fs_src/style.css
As a follow up to #1083:
- Adding support of Dark Mode.
- Fixing some UI issues.
=> Support Dark Mode & UI issues fix

src/ShellyUNI/shelly_init.cpp
This fixes https://github.com/mongoose-os-apps/shelly-homekit/issues/715 for me @timoschilling ?
=> ShellyUni: use noisyinputpin for debouncing

.github/workflows/Dockerfile-esp32-build, .github/workflows/shelly-homekit.yaml
Many tanks to @markirb for https://github.com/cesanta/mongoose-os/pull/603
=> use custom build of mgos/esp32-build docker image

fs_src/script.js
=> improve rgbw and cct labeling

fs_src/script.js
=> improve power meter

fs_src/index.html, fs_src/script.js, mos.yml, src/shelly_hap_outlet.cpp, src/shelly_hap_switch.cpp, src/shelly_switch.cpp
=> option to invert hap state

fs_src/index.html, fs_src/script.js, src/shelly_rpc_service.cpp, src/shelly_wifi_config.cpp, src/shelly_wifi_config.hpp, src/wifi_config/shelly_wifi_config_impl.cpp
UI would be make a bit nicer after a little ui overhaul.
=> make nameserver configurable

src/shelly_output.cpp
=> fix pwm behavior at 100%

fs_src/script.js
=> fix code gen with non alphanum chars ssid

README.md
preview: https://github.com/mongoose-os-apps/shelly-homekit/blob/new-readme/README.md
=> refactor supported device list
